"""Add is_deleted to document

Revision ID: 0423890795a8
Revises: 4112356551bf
Create Date: 2026-08-12 20:22:10.353940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0423890795a8'
down_revision: Union[str, None] = '4112356551bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS financerecordtypeenum CASCADE")
    op.execute("DROP TYPE IF EXISTS financerecordstatusenum CASCADE")
    op.create_table('financerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('record_type', sa.Enum('budget', 'expense', 'salary', 'vendor_payment', 'renewal', 'revenue', 'other', name='financerecordtypeenum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'overdue', 'rejected', name='financerecordstatusenum'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('cost_category', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financerecord_id'), 'financerecord', ['id'], unique=False)
    op.create_table('performancereview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('salary_before', sa.Float(), nullable=True),
    sa.Column('salary_after', sa.Float(), nullable=True),
    sa.Column('increment_pct', sa.Float(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performancereview_id'), 'performancereview', ['id'], unique=False)
    op.create_table('issuefollowup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issuefollowup_id'), 'issuefollowup', ['id'], unique=False)
    op.execute('ALTER TABLE issue ADD COLUMN IF NOT EXISTS deadline VARCHAR')
    op.execute('ALTER TABLE issue ADD COLUMN IF NOT EXISTS reported_by_id INTEGER REFERENCES "user"(id)')
    op.create_foreign_key(None, 'issue', 'user', ['reported_by_id'], ['id'])
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS salary FLOAT')
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS performance_score FLOAT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'performance_score')
    op.drop_column('user', 'salary')
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_column('issue', 'reported_by_id')
    op.drop_column('issue', 'deadline')
    op.drop_index(op.f('ix_issuefollowup_id'), table_name='issuefollowup')
    op.drop_table('issuefollowup')
    op.drop_index(op.f('ix_performancereview_id'), table_name='performancereview')
    op.drop_table('performancereview')
    op.drop_index(op.f('ix_financerecord_id'), table_name='financerecord')
    op.drop_table('financerecord')
    # ### end Alembic commands ###
