"""Add performance review

Revision ID: 671ace7a50e2
Revises: e05d81e7a4a3
Create Date: 2026-09-28 14:22:45.950947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '671ace7a50e2'
down_revision: Union[str, None] = 'e05d81e7a4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financerecord', sa.Column('record_type', sa.Enum('budget', 'expense', 'salary', 'vendor_payment', 'renewal', 'revenue', 'other', name='financerecordtypeenum'), nullable=True))
    op.add_column('financerecord', sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'overdue', 'rejected', name='financerecordstatusenum'), nullable=True))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('task_idempotency_key_key', 'task', type_='unique')
    op.drop_index('ix_task_idempotency_key', table_name='task')
    op.create_index(op.f('ix_task_idempotency_key'), 'task', ['idempotency_key'], unique=True)
    op.create_foreign_key(None, 'task', 'user', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'task', 'task', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'task', 'quarter', ['quarter_id'], ['id'])
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'ceo', 'manager', 'team_lead', 'employee', name='roleenum'),
               type_=sa.String(),
               existing_nullable=True)
#     op.alter_column('user', 'google_token_expires_at',
#                existing_type=sa.VARCHAR(),
#                type_=sa.DateTime(),
#                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('user', 'google_token_expires_at',
#                existing_type=sa.DateTime(),
#                type_=sa.VARCHAR(),
#                existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('super_admin', 'admin', 'ceo', 'manager', 'team_lead', 'employee', name='roleenum'),
               existing_nullable=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_idempotency_key'), table_name='task')
    op.create_index('ix_task_idempotency_key', 'task', ['idempotency_key'], unique=False)
    op.create_unique_constraint('task_idempotency_key_key', 'task', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('task', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('financerecord', 'status')
    op.drop_column('financerecord', 'record_type')
    # ### end Alembic commands ###
