"""Add targets and permissions

Revision ID: 673a88fb5921
Revises: de529221ca51
Create Date: 2026-09-07 09:26:46.560508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '673a88fb5921'
down_revision: Union[str, None] = 'de529221ca51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scored_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scored_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_id'), 'target', ['id'], unique=False)
    op.create_index(op.f('ix_target_month'), 'target', ['month'], unique=False)
    op.create_index(op.f('ix_target_title'), 'target', ['title'], unique=False)
    op.create_table('target_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grantee_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('can_score', sa.Boolean(), nullable=True),
    sa.Column('can_add_targets', sa.Boolean(), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['grantee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_permission_id'), 'target_permission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_target_permission_id'), table_name='target_permission')
    op.drop_table('target_permission')
    op.drop_index(op.f('ix_target_title'), table_name='target')
    op.drop_index(op.f('ix_target_month'), table_name='target')
    op.drop_index(op.f('ix_target_id'), table_name='target')
    op.drop_table('target')
    # ### end Alembic commands ###
