"""Add issue assignment fields

Revision ID: 917228eda225
Revises: c4244475a54a
Create Date: 2026-08-17 23:39:26.723328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917228eda225'
down_revision: Union[str, None] = 'c4244475a54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('issue_type', sa.String(), nullable=True, server_default='general'))
    op.add_column('issue', sa.Column('assignment_status', sa.String(), nullable=True))
    op.add_column('issue', sa.Column('assignment_timestamp', sa.DateTime(), nullable=True))
    op.add_column('issue', sa.Column('declined_by_users', sa.JSON(), nullable=True, server_default='[]'))
    
    op.add_column('financerecord', sa.Column('record_type', sa.Enum('budget', 'expense', 'salary', 'vendor_payment', 'renewal', 'revenue', 'other', name='financerecordtypeenum'), nullable=True))
    op.add_column('financerecord', sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'overdue', 'rejected', name='financerecordstatusenum'), nullable=True))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'task', 'quarter', ['quarter_id'], ['id'])
    op.create_foreign_key(None, 'task', 'task', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['reviewer_id'], ['id'])
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'ceo', 'manager', 'team_lead', 'employee', name='roleenum'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'google_token_expires_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_token_expires_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('super_admin', 'admin', 'ceo', 'manager', 'team_lead', 'employee', name='roleenum'),
               existing_nullable=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('financerecord', 'status')
    op.drop_column('financerecord', 'record_type')
    # ### end Alembic commands ###
