"""add_task_schedule_columns

Revision ID: 9fa37d90047f
Revises: 013e7c58e85b
Create Date: 2026-07-27 15:38:50.694117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa37d90047f'
down_revision: Union[str, None] = '013e7c58e85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('scheduled_date', sa.String(), nullable=True))
    op.add_column('task', sa.Column('scheduled_start_time', sa.String(), nullable=True))
    op.add_column('task', sa.Column('scheduled_end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'scheduled_end_time')
    op.drop_column('task', 'scheduled_start_time')
    op.drop_column('task', 'scheduled_date')
    # ### end Alembic commands ###
