"""add_issue_assignment_fields

Revision ID: c4244475a54a
Revises: 0423890795a8
Create Date: 2026-08-17 20:04:06.870073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4244475a54a'
down_revision: Union[str, None] = '0423890795a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('issue_type', sa.Enum('bug', 'feature', 'general', name='issuetypeenum'), nullable=True))
    op.add_column('issue', sa.Column('assignment_status', sa.Enum('pending_acceptance', 'accepted', name='issueassignmentstatusenum'), nullable=True))
    op.add_column('issue', sa.Column('assignment_timestamp', sa.DateTime(), nullable=True))
    op.add_column('issue', sa.Column('declined_by_users', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'issue', 'user', ['reported_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_column('issue', 'declined_by_users')
    op.drop_column('issue', 'assignment_timestamp')
    op.drop_column('issue', 'assignment_status')
    op.drop_column('issue', 'issue_type')
    # ### end Alembic commands ###
