"""Add target_score

Revision ID: e05d81e7a4a3
Revises: 673a88fb5921
Create Date: 2026-09-11 11:26:34.684507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e05d81e7a4a3'
down_revision: Union[str, None] = '673a88fb5921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'reviewer_id', name='uix_target_reviewer')
    )
    op.create_index(op.f('ix_target_score_id'), 'target_score', ['id'], unique=False)
    op.create_index(op.f('ix_target_score_target_id'), 'target_score', ['target_id'], unique=False)

    # Data migration: copy existing scores from target to target_score
    op.execute("""
        INSERT INTO target_score (target_id, reviewer_id, score, created_at, updated_at)
        SELECT id, scored_by_id, score, NOW(), NOW()
        FROM target
        WHERE score IS NOT NULL AND scored_by_id IS NOT NULL
        ON CONFLICT DO NOTHING;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_idempotency_key'), table_name='task')
    op.drop_index(op.f('ix_target_score_target_id'), table_name='target_score')
    op.drop_index(op.f('ix_target_score_id'), table_name='target_score')
    op.drop_table('target_score')
    # ### end Alembic commands ###
